music_news_feed/albums/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'albums'
urlpatterns = [
    url(r'^feed', views.feed, name='feed'),
    url(r'^album', views.tracks_of_album, name='tracks_of_album'),
]

music_news_feed/artists/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'artists'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search_artists', views.search_artists, name='search_artists'),
    url(r'^favorite_artists', views.favorite_artists, name='favorite_artists'),
]

music_news_feed/index/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

music_news_feed/music_news_feed/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from profiles import views as profile_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    #path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    #url(r'^(?:index/|$)', include('index.urls')),
    url(r'^$', profile_views.home, name='home'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    url(r'^signup/$', profile_views.signup, name='signup'),
    url(r'^artists/', include('artists.urls')),
    url(r'^albums/', include('albums.urls')),
]

music_news_feed/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Music News Feed{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'bootstrap/4.0.0-beta/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery-3.2.1.min.js' %}"></script>
    <style type="text/css">
        .container {
            max-width: 80%;
            width: 80%;
            margin-top: 0px;
        }
    </style>
  </head>
  <body>
    <div class="container">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
        <a class="navbar-brand" href="/">Music News Feed</a>
	{% if user.is_authenticated %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'artists:index' %}">Исполнители</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'albums:feed' %}">Лента</a>
            </li>
        </ul>
	{% endif %}
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
	    <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">выйти</a>
	    </li>
            {% else %}
	    <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">войти</a>
	    </li>
	    <li class="nav-item">
    	        <a class="nav-link" href="{% url 'signup' %}">зарегистрироваться</a>
	    </li>
            {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    </div>
  </body>
</html>

music_news_feed/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>Привет, {{ user.get_full_name }} <small>({{ user.username }})</small>!</h2>
  <p>Ваша дата рождения: {{ user.profile.birth_date }}</p>
  <br>
  <h4>Выберите раздел:</h4>
      <ul>
          <li>
              <a href="{% url 'artists:index' %}">Исполнители</a>
          </li>
          <li>
	      <a href="{% url 'albums:feed' %}">Лента</a>
          </li>
       </ul>
{% endblock %}

music_news_feed/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Вход</h2>
  {% if form.errors %}
    <p style="color: red">Неправильный логин или пароль. Попробуйте снова.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Войти</button>
    <a href="{% url 'signup' %}">Новый пользователь? Зарегистрируйтесь</a>
  </form>
{% endblock %}

music_news_feed/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Регистрация</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Зарегистрироваться</button>
  </form>
{% endblock %}