music_news_feed/albums/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'albums'
urlpatterns = [
    url(r'^feed', views.feed, name='feed'),
    url(r'^album', views.tracks_of_album, name='tracks_of_album'),
]

music_news_feed/index/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

music_news_feed/music_news_feed/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from profiles import views as profile_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    #path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    #url(r'^(?:index/|$)', include('index.urls')),
    url(r'^$', profile_views.home, name='home'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    url(r'^signup/$', profile_views.signup, name='signup'),
    url(r'^artists/', include('artists.urls')),
    url(r'^albums/', include('albums.urls')),
]

music_news_feed/albums/models.py
from django.db import models
from enum import Enum
from artists.models import Artists
from django.contrib.auth.models import User


class AlbumTypes(Enum):
    LP = 'album'
    SP = 'single'
    CP = 'compilation'


class Albums(models.Model):
    name = models.CharField(max_length=255)
    album_type = models.CharField(max_length=15, choices=[(tag, tag.value) for tag in AlbumTypes])
    genres = models.CharField(max_length=4096)
    spotify_id = models.CharField(max_length=64)
    img_url = models.URLField(blank=True)
    release_date = models.DateField()
    artists = models.ManyToManyField(Artists)
    users = models.ManyToManyField(User, through='Updates', related_name='album_updates')

    @classmethod
    def get_or_none(cls, **kwargs):
        try:
            return cls.objects.get(**kwargs)
        except Albums.DoesNotExist:
            return None


class Updates(models.Model):
    person = models.ForeignKey(User, on_delete=models.CASCADE)
    album = models.ForeignKey(Albums, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

music_news_feed/albums/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings

from django.shortcuts import render, render_to_response, redirect, reverse, redirect
from spotify_client import scripts
from django.urls import reverse


def feed(r):
    form = {
        'album_to_change': r.GET.get('album_to_change', ''),
    }

    if form['album_to_change']:
        scripts.change_updates_status(form['album_to_change'], r.user)
        return redirect(reverse('albums:feed'))

    albums = scripts.feed_of_user(r.user)
    return render(r, 'albums/feed.html', {'feed': albums})


def tracks_of_album(r):
    form = {
        'album': r.GET.get('album', ''),
    }
    album = scripts.tracks_of_album(form['album'])
    return render(r, 'albums/album.html', {'album': album})

music_news_feed/albums/templates/albums/album.html
{% extends 'base.html' %}

{% block content %}
  <h1>Альбом</h1>
  <table id="album_table" class="table table-hover" style="margin-top: 20px;">
      <thead style='display:none;'>
          <colgroup>
              <col style="width:12%;" />
              <col style="width:17%;" />
              <col style="width:17%;" />
              <col style="width:17%;" />
	      <col style="width:17%;" />
          </colgroup>
          <tr>
              <th>Обложка</th>
	      <th>Название</th>
	      <th>Исполнитель</th>
              <th>Жанры</th>
	      <th>Дата релиза</th>
          </tr>
      </thead>
      <tbody>
          <tr>
             <td>
	         {% if album.img_url %}
 	         <img src="{{ album.img_url }}" alt="{{ album.name }}" style="width:90%; height: auto">
	         {% endif %}
             </td>
             <td>
                 {{ album.name }}
             </td>
             <td>
                 {{ album.artists|join:", " }}
             </td>
             <td>
                 {{ album.genres|join:", " }}
             </td>
             <td>
                 {{ album.release_date }}
             </td>
           </tr>
       </tbody>
   </table>
   <table id="tracks_table" class="table table-hover" style="margin-top: 20px;">
      <thead>
          <colgroup>
              <col style="width:12%;" />
              <col style="width:17%;" />
              <col style="width:17%;" />
              <col style="width:17%;" />
              <col style="width:17%;" />
          </colgroup>
          <tr>
              <th>#</th>
              <th>Название</th>
              <th>Исполнитель</th>
              <th>Длительность</th>
          </tr>
      </thead>
      <tbody>
          {% for track in album.tracks %}
          <tr>
             <td>
		 {{ track.track_number }}
             </td>
             <td>
                 {{ track.name }}
             </td>
             <td>
                 {{ album.artists|join:", " }}
             </td>
             <td>
                 {{ track.duration_ms }}
             </td>
          </tr>
          {% endfor %}
       </tbody>
   </table>
{% endblock %}

music_news_feed/albums/templates/albums/feed.html
{% extends 'base.html' %}

{% block content %}
<h1>Лента альбомов</h1>
  <table id="feed_table" class="table table-hover" style="margin-top: 20px;">
      <thead>
          <colgroup>
              <col style="width:12%;" />
              <col style="width:17%;" />
              <col style="width:17%;" />
              <col style="width:17%;" />
	      <col style="width:17%;" />
	      <col style="width:17%;" />
          </colgroup>
          <tr>
              <th>Обложка</th>
	      <th>Название</th>
	      <th>Исполнитель</th>
              <th>Жанры</th>
	      <th>Дата релиза</th>
              <th>Просмотрено</th>
          </tr>
      </thead>
      <tbody>
           {% for album in feed %}
              <tr{% if album.status %} style="background-color:lightgrey"{% endif %}>
                 <td>
	             {% if album.img_url %}
 		     <img src="{{ album.img_url }}" alt="{{ album.name }}" style="width:90%; height: auto">
		     {% endif %}
                 </td>
                 <td>
 		     <a href="{% url 'albums:tracks_of_album' %}?album={{ album.spotify_id }}">{{ album.name }}</a>
                 </td>
                 <td>
                     {{ album.artists_name|join:", " }}
                 </td>
                 <td>
                     {{ album.genres|join:", " }}
                 </td>
                 <td>
                     {{ album.release_date }}
                 </td>
                 <td>
		     <a href="{% url 'albums:feed' %}?album_to_change={{ album.spotify_id }}">{% if album.status %}отметить как не прослушанное{% else %}отметить как прослушанное{% endif %}</a>
                 </td>
              </tr>
           {% endfor %}
       </tbody>
   </table>
{% endblock %}